open keyword "C:\Users\surya\OneDrive\Desktop\Readings\rx -20 ryr 0.7.txt"
Time to read keyword file = 0.203 seconds
Time to process element data = 0.016 seconds
Finished reading model
quat 0.000000 0.707107 0.707107 0.000000;
open keyword "C:\Users\surya\OneDrive\Desktop\Readings\neutral.txt"
Time to read keyword file = 0.148 seconds
Time to process element data = 0.008 seconds
Finished reading model
open keyword "C:\Users\surya\OneDrive\Desktop\Readings\rx -30 ryr 1.1.txt"
Time to read keyword file = 0.125 seconds
Time to process element data = 0.008 seconds
Finished reading model
Save Config. parameters to file C:\Users\surya\AppData\Roaming\LSTC\LS-PrePost4.8\lsppconf
